import { type RouteConfig, index, route } from '@react-router/dev/routes'

export default [
  index('../src/routes/_index.tsx'),
  route('about', '../src/routes/about.tsx'),
  route('contact', '../src/routes/contact.tsx'),
  route('integrations', '../src/routes/integrations.tsx'),
  route('security', '../src/routes/security.tsx'),
  route('case-studies', '../src/routes/case-studies.tsx'),
  route('case-studies/:slug', '../src/routes/case-studies-slug.tsx'),
  route('blog', '../src/routes/blog.tsx'),
  route('blog/:slug', '../src/routes/blog-slug.tsx'),
  route('author/michael-shahid', '../src/routes/author-michael-shahid.tsx'),
  route('privacy', '../src/routes/privacy.tsx'),
  route('terms', '../src/routes/terms.tsx'),
  route('comparisons', '../src/routes/comparisons.tsx'),
  route('pricing', '../src/routes/pricing.tsx'),
  route('resources', '../src/routes/resources.tsx'),
  route('inventory-management', '../src/routes/inventory-management.tsx'),
  route('login', '../src/routes/login.tsx'),
  route('signup', '../src/routes/signup.tsx'),
  route('verify-email', '../src/routes/verify-email.tsx'),
  route('reset-password', '../src/routes/reset-password.tsx'),
  route('dashboard', '../src/routes/dashboard.tsx'),
  route('admin', '../src/routes/admin.tsx'),
] satisfies RouteConfig
